#!/usr/bin/env bash
# This script displays information about subdomains

# Function to display info about a subdomain
display_info() {
    local domain="$1"
    local subdomain="$2"
    local record_info
    record_info=$(dig "$subdomain"."$domain" +short -t A)

    if [[ -n "$record_info" ]]; then
        echo "The subdomain $subdomain is a A record and points to $record_info"
    else
        echo "The subdomain $subdomain does not have an A record"
    fi
}

# Main script
domain="$1"
subdomain="$2"

if [[ -n "$domain" ]]; then
    if [[ -n "$subdomain" ]]; then
        display_info "$domain" "$subdomain"
    else
        for subdomain in www lb-01 web-01 web-02; do
            display_info "$domain" "$subdomain"
        done
    fi
else
    echo "Usage: $0 domain [subdomain]"
    exit 1
fi
