#!/usr/bin/env bash
# The script displays information about subdomains

# display subdomain information
get_subdomain_info() {
  domain="$1"
  subdomain="$2"
  dig_output=$(dig "$subdomain.$domain" | grep -A1 'ANSWER SECTION:')
  record_type=$(echo "$dig_output" | awk '{print $4}')
  destination=$(echo "$dig_output" | awk '{print $5}')
  echo "The subdomain $subdomain is a $record_type record and points to $destination"
}

# Main script
domain="$1"
subdomain="$2"

if [ -z "$subdomain" ]; then
  # No specific subdomain provided, display information for default subdomains
  get_subdomain_info "$domain" www
  get_subdomain_info "$domain" lb-01
  get_subdomain_info "$domain" web-01
  get_subdomain_info "$domain" web-02
else
  # Display information for the specified subdomain
  get_subdomain_info "$domain" "$subdomain"
fi
