#!/usr/bin/env bash
# Usage: ./1-world_wide_web <domain> <subdomain>

Domain="$1"
subdomain="$2"

if [ -z "$subdomain" ]; then
  subdomains=("www" "lb-01" "web-01" "web-02")
else
  subdomains=("$subdomain")
fi

for sub in "${subdomains[@]}"
do
  result=$(dig "$sub.$domain" | awk '/^'${sub}'\.'${domain}'\./{print}')
  record_type=$(echo "$result" | awk '{print $4}')
  destination=$(echo "$result" | awk '{print $5}')
  echo "The subdomain $sub is a $record_type record and points to $destination"
done
