#!/usr/bin/env bash
# configure web-02 to be identical to web-01
# The name of a custom HTTP header must be X-Served-By
# The value of a custom HTTP header must be the hostname
# of the server Nginx is running on
# sudo sed -i 's/server_name _;.*/server_name _;\n\tadd_header
# X-Served-By \$hostname;/' /etc/nginx/sites-enabled/default 
# Updating Packages before performing installations
# Installs Nginx with the following configurations:
#+    Listens on the port 80.
#+    Returns a page containing a "Hello World!" when queried
#+     at the root with a curl GET request.
#+    Configures /redirect_me as a "301 Moved Permanently".
#+    Includes the custom 404 page containing "Ceci n'est pas une page".
#+    Contains a custom HTTP header named X-Served-By.
#+    The value of the HTTP header is the hostname of the running server.

apt-get install -y nginx

mkdir -p /var/www/html
touch /var/www/html/index.html
echo "Hello World!" > /var/www/html/index.html
touch /var/www/html/404.html
echo "Ceci n'est pas une page" > /var/www/html/404.html

printf %s "server {
    listen 80 default_server;
    listen [::]:80 default_server;
    add_header X-Served-By $HOSTNAME;
    root   /var/www/html;
    index  index.html index.htm;

    location /redirect_me {
        return 301 http://linkedin.com/;
    }

    error_page 404 /404.html;
    location /404 {
      root /var/www/html;
      internal;
    }
}" > /etc/nginx/sites-available/default

service nginx restart
