#!/usr/bin/env bash
# Create the script to install and configure HAProxy on lb-01 server.
# Configure HAProxy to send traffic to web-01 and web-02 servers.
# Distribute requests using the roundrobin algorithm.
# Make sure that HAProxy can be managed via an init script

# Install and configure HAproxy on my lb-01 server.
sudo apt-get install -y haproxy

echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

cat <<EOT | sudo tee -a /etc/haproxy/haproxy.cfg
frontend Randommall.tech
    timeout client  30000
    bind 0:80
    default_backend Randommall.tech_backend

backend Randommall.tech_backend
    timeout connect  3000
    timeout server  30000
    balance roundrobin
    server 435322-web-01 54.90.51.191:80 check
    server 435322-web-02 52.3.251.97:80 check
EOT

sudo service haproxy restart
