#!/usr/bin/env bash
# Function Name: ManageMyProcess
# Parameters: Command (start, stop, restart)
# Description: This script manages the manage_my_process program.
#It can start, stop, or restart the program based
#on the command-line argument provided.
# Return: None. The script performs the requested
#action on the manage_my_process program.

FILE="/var/run/my_process.pid"
create()
{
    sudo touch $FILE
    sudo bash -c "echo $$ > $FILE"
}

if [ "$1" == "start" ]; then
    create
    ./manage_my_process &
    echo "manage_my_process started"

elif [ "$1" == "stop" ]
then
    [ -e "/var/run/my_process.pid" ] && sudo pkill -f "./manage_my_process" && rm /var/run/my_process.pid
    echo "manage_my_process stopped"

elif [ "$1" == "restart" ]
then
    $0 stop >& /dev/null
    $0 start >& /dev/null
    echo "manage_my_process restarted"

else
    echo "Usage: manage_my_process {start|stop|restart}"
fi
