#!/usr/bin/env bash
# Description: This script displays the PID and process name of
#all currently running processes that contain the word "bash".
# Return: Outputs a list of PIDs and process names for all
#currently running processes that contain the word "bash".
#If the script fails, it returns a non-zero status code.

pgrep -l bash
