#!/usr/bin/env bash
# Function Name: KillInfinityMessage
# Parameters: None
# Description: This script stops the 4-to_infinity_and_beyond
#process using the SIGTERM signal.
# Return: None. The script sends a termination signal
#to the 4-to_infinity_and_beyond process.

# Get the pid of the program
id=$(pgrep "bash ./4-to_infinity_and_beyond" -f)

# Terminate the infinite process
if [ -n "$id" ]
then
  kill -15 "$id"
fi
