#!/bin/bash
# Function Name: Main
# Parameters: None
# Description: This script checks if the process
#'4-to_infinity_and_beyond' is running and terminates it if it is.
# Return: None

# Get the PID of the process
pid=$(pgrep -f 4-to_infinity_and_beyond)

# Check if the process is running
if [[ -n $pid ]]; then
    # Send a SIGTERM signal to the process
    pkill -f 4-to_infinity_and_beyond
    echo "Process 4-to_infinity_and_beyond has been terminated."
else
    echo "Process 4-to_infinity_and_beyond is not running."
fi
