#!/usr/bin/env bash

# Function Name: KillInfinityMessage
# Parameters: None
# Description: This script stops the 4-to_infinity_and_beyond process using the SIGTERM signal.
# Return: None. The script sends a termination signal to the 4-to_infinity_and_beyond process.

# Terminate the infinite process
pkill -15 "bash ./4-to_infinity_and_beyond" -f
