#!/usr/bin/env bash
# Script Name: Terminate Infinity and Beyond
# Description: This script kills the
#'4-to_infinity_and_beyond' program using the SIGTERM signal.

# Terminate the infinite process
# The -15 option sends the SIGTERM signal to the process.
# The -f option matches against the entire command line.
pkill -15 "bash ./4-to_infinity_and_beyond" -f
