#!/usr/bin/env bash
# Description: This script displays the string "Best School" 10 times.

for (( f=1; f<=10; f++ ))  # f is the loop variable, ranging from 1 to 10
do
    echo "Best School"  # Prints "Best School" to the console
done
