#!/usr/bin/env bash

# Function: main
# Parameters: None
# Description: This script displays the string "Best School" 10 times.
# Return: None

for (( c=1; c<=10; c++ ))  # c is the loop variable, ranging from 1 to 10
do
    echo "Best School"  # Prints "Best School" to the console
done
