#!/usr/bin/env bash
# Description: This script reads the /etc/passwd file and displays the username, user id, and home directory for each user.

while IFS=: read -r username _ userid _ _ homedir _  # Read the /etc/passwd file
do
    echo "$username:$userid:$homedir"  # Print the username, user id, and home directory
done < /etc/passwd
