#!/usr/bin/env bash
# Description: This script displays the string "Best School" 10 times.

t=1
while (( t<=10 ))  # t is the loop variable, ranging from 1 to 10
do
    echo "Best School"  # Prints "Best School" to the console
    ((t++))  # Increment the loop variable
done
