#!/usr/bin/env bash
# Description: This script displays numbers from 1 to 20, and prints "bad luck from China" on the 4th iteration, "bad luck from Japan" on the 9th iteration, and "bad luck from Italy" on the 17th iteration.

p=1
while (( p<=20 ))  # p is the loop variable, ranging from 1 to 20
do
    echo "$p"
    case $p in
        4)
            echo "bad luck from China"
            ;;
        9)
            echo "bad luck from Japan"
            ;;
        17)
            echo "bad luck from Italy"
            ;;
    esac
    ((p++))  # Increment the loop variable
done
