#!/usr/bin/env bash
# This script changes the localhost address
# and adds a new entry to the hosts file.

# Copies the current hosts file to a new file
# in the home directory.
cp /etc/hosts ~/hosts.new

# Replaces the localhost address (127.0.0.1) 
# with a new address (127.0.0.2) in the new hosts file.
sed -i "s/^127[0-9.]*\slocalhost/127.0.0.2 localhost/" ~/hosts.new

# Adds a new entry to the hosts file to redirect
#requests for facebook.com to 8.8.8.8.
sed -i "$ a\8.8.8.8 facebook.com" ~/hosts.new

# Replaces the original hosts file with the modified one.
cp -f ~/hosts.new /etc/hosts
